# Generated by Django 4.1.4 on 2022-12-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hashtag',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
