# Generated by Django 4.1.4 on 2022-12-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='genre',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='url',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
